final List<String> FourWheeler =
[
  "Honda",
  "Mahindra",
  "BMW",
  "22 KYMCO",
  "Aftek Motors",
  "Ampere Bikes",
  "Aprilia",
  "Ather Energy",
  "Avan Motors",
  "Avon Bikes",
  "Bajaj",
  "Benelli ",
  "Big Dog Motorcycle",
  "CF Moto",
  "Cleveland Cyclewerks",
  "Ducati",
  "Emflux Motors",
  "Gogoro",
  "Harley-Davidson",
  "Hero",
  "Hero Electric",
  "Hero Honda",
  "Hysoung",
  "Indian",
  "Kawasaki",
  "Kinetic",
  "KTM",
  "Li-ions Elektrik Solutions",
  "LML",
  "Mahindra GenZe",
  "Moto Guzzi",
  "MV Agusta ",
  "Norton ",
  "Okinawa Scooters",
  "Palatino",
  "Piaggio ",
  "Revolt Motors",
  "Royal Enfield",
  "Suzuki",
  "SWM",
  "Tork Motors",
  "Triumph",
  "TVS",
  "Ultraviolette",
  "UM Moter cycle",
  "Yamaha",
  "Yezdi",
  "Benelli",
  "Piaggio",
  "Husqvarna Motorcycles",
  "Jawa Moto",
  "MV Agusta",
  "Norton",
  "UM Motorcycles",
  "YO Bykes"
];

final List<String> TwoWheelerHondaVehical = [
  "Activa",
  "Activa 125",
  "Aviator",
  "CB 1000R Plus",
  "CB Hornet 160r",
  "CB Shine",
  "CB Trigger",
  "CB Twister",
  "CB Unicorn",
  "CB Unicorn 160",
  "CB500X",
  "CB650R",
  "CBF 1000L Africa Twin",
  "CBF Stunner",
  "CBR 150R",
  "CBR 250R",
  "CBR 300R",
  "CBR 650R",
  "CBR1000RR-R",
  "CD 110",
  "CRF 1100L Africa",
  "Twin",
  "Cliq",
  "Dio",
  "Dream Neo",
  "Dream Yuga",
  "Eterno",
  "Forzaa 300",
  "Gold Wing",
  "Grazia",
  "Grazia 125",
  "Livo",
  "Navi",
  "SP 125",
  "X Blade"
];


final List<String> fueltype = [
  "Petrol",
  "diesel",
  "electric",
];


final List<String> Transmission = [
  "With Geor",
  "without Geaor",
];

